SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";

CREATE TABLE IF NOT EXISTS `posts`(
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `body` TEXT NOT NULL,
  `date_added` DATE NOT NULL,
  `added_by` VARCHAR(255) NOT NULL,
  `user_posted_to` VARCHAR(255) NOT NULL,
  PRIMARY KEY(`id`)
) ENGINE = MyISAM DEFAULT CHARSET = latin1 AUTO_INCREMENT = 10;






